/**
 * Conflict detector — detects stage disagreements and structural conflicts
 * in the knowledge graph after all stages have run.
 *
 * Detects:
 * - Runtime-unconfirmed: AST+TIA say covered, but IAST/DAST disagree
 * - DAST-unreachable: DAST probed an endpoint but could not reach it
 * - Undeclared-endpoint: DAST discovered endpoints not found by static analysis
 * - Stage disagreement: Two stages assign different types to the same node
 */

import type { ConflictNode, ConflictType, StageName } from '../../types';
import type { CoverageKnowledgeGraph } from '../../graph';
import type { IastOutput } from '../iast/types';
import type { DastOutput } from '../dast/types';

/**
 * Detect conflicts across all stages.
 */
export function detectConflicts(
  graph: CoverageKnowledgeGraph,
  iastOutput: IastOutput | undefined,
  dastOutput: DastOutput | undefined,
): ConflictNode[] {
  const conflicts: ConflictNode[] = [];

  // 1. Runtime-unconfirmed: endpoints that AST found but neither IAST nor DAST confirmed
  const endpointNodes = graph.getNodesByType('endpoint');
  const iastConfirmed = new Set(iastOutput?.confirmedEndpoints ?? []);
  const dastConfirmed = new Set(dastOutput?.confirmedEndpoints ?? []);
  const dastUnreachable = new Set(dastOutput?.unreachableEndpoints ?? []);

  const hasRuntimeData = (iastOutput?.events.length ?? 0) > 0 || (dastOutput?.results.length ?? 0) > 0;

  if (hasRuntimeData) {
    for (const node of endpointNodes) {
      // Only check endpoints from static stages (AST/TIA)
      if (node.sourceStage !== 'ast' && node.sourceStage !== 'sca') continue;

      const confirmed = iastConfirmed.has(node.id) || dastConfirmed.has(node.id);
      const unreachable = dastUnreachable.has(node.id);

      if (!confirmed && !unreachable) {
        conflicts.push({
          conflictId: `conflict:runtime-unconfirmed:${node.id}`,
          nodeId: node.id,
          type: 'runtime-unconfirmed',
          stages: getRuntimeStages(iastOutput, dastOutput),
          stageOutputs: {
            ast: 'endpoint-declared',
            iast: iastConfirmed.has(node.id) ? 'confirmed' : 'not-observed',
            dast: dastConfirmed.has(node.id) ? 'confirmed' : 'not-probed',
          },
          detail: `${node.label} was found by static analysis but not confirmed by any runtime stage.`,
          suggestedAction: 'Check if the endpoint is covered by integration/e2e tests that produce IAST events or DAST probes.',
          severity: 'info',
        });
      }
    }
  }

  // 2. DAST-unreachable: endpoints that DAST explicitly could not reach
  if (dastOutput) {
    for (const endpointId of dastUnreachable) {
      const node = graph.getNode(endpointId);
      const label = node?.label ?? endpointId;

      conflicts.push({
        conflictId: `conflict:dast-unreachable:${endpointId}`,
        nodeId: endpointId,
        type: 'dast-unreachable',
        stages: ['dast'],
        stageOutputs: {
          dast: 'unreachable',
        },
        detail: `${label} was probed by DAST but could not be reached.`,
        suggestedAction: 'Verify the endpoint is deployed and accessible. Check authentication requirements and network configuration for the DAST scanner.',
        severity: 'warning',
      });
    }
  }

  // 3. Undeclared-endpoint: DAST discovered endpoints not found by static analysis
  if (dastOutput) {
    const staticEndpointIds = new Set(
      endpointNodes
        .filter((n) => n.sourceStage !== 'dast')
        .map((n) => n.id),
    );

    for (const result of dastOutput.results) {
      if (!result.reachable) continue;

      const endpointPath = result.normalizedPath ?? result.path;
      const endpointId = `endpoint:${result.method.toUpperCase()}:${endpointPath}`;

      if (!staticEndpointIds.has(endpointId)) {
        // Avoid duplicate conflicts for the same endpoint
        const conflictId = `conflict:undeclared-endpoint:${endpointId}`;
        if (conflicts.some((c) => c.conflictId === conflictId)) continue;

        conflicts.push({
          conflictId,
          nodeId: endpointId,
          type: 'undeclared-endpoint',
          stages: ['dast'],
          stageOutputs: {
            dast: 'discovered',
            ast: 'not-declared',
          },
          detail: `${result.method.toUpperCase()} ${endpointPath} was discovered by DAST but not found by static analysis.`,
          suggestedAction: 'Review the endpoint source. It may be dynamically registered, generated by a framework, or missing from the scanned codebase.',
          severity: 'warning',
        });
      }
    }
  }

  // 4. Stage disagreement: same node ID added by multiple stages with different types
  // (This is handled by the graph merge(), which already returns ConflictNode[])

  return conflicts;
}

function getRuntimeStages(
  iastOutput: IastOutput | undefined,
  dastOutput: DastOutput | undefined,
): StageName[] {
  const stages: StageName[] = ['ast'];
  if (iastOutput && iastOutput.events.length > 0) stages.push('iast');
  if (dastOutput && dastOutput.results.length > 0) stages.push('dast');
  return stages;
}
