/**
 * Feature 28 — Tests for TestGenerationEngine
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { TestGenerationEngine, generateTests } from '../../src/generation/engine';
import type { GenerationOptions } from '../../src/generation/types';

describe('TestGenerationEngine', () => {
  let tmpDir: string;
  let reportsDir: string;
  let outDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'gen-test-'));
    reportsDir = path.join(tmpDir, 'reports');
    outDir = path.join(tmpDir, 'generated-tests');
    fs.mkdirSync(reportsDir, { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  describe('dry-run mode', () => {
    it('should not write files in dry-run mode', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P0',
      };

      const result = await generateTests(opts);

      expect(result.dryRun).toBe(true);
      expect(fs.existsSync(outDir)).toBe(false);
    });

    it('should produce GeneratedFile content in dry-run mode', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P1',
      };

      const result = await generateTests(opts);

      expect(result.files.length).toBeGreaterThan(0);
      for (const file of result.files) {
        expect(typeof file.content).toBe('string');
        expect(file.content.length).toBeGreaterThan(0);
        expect(typeof file.gapId).toBe('string');
        expect(file.gapId.length).toBeGreaterThan(0);
        expect(typeof file.relativePath).toBe('string');
        expect(file.relativePath).not.toBe('');
      }
    });
  });

  describe('file generation', () => {
    it('should write files when dryRun is false', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: false,
        priority: 'P1',
        noSecurity: true,
        noCypress: true,
      };

      const result = await generateTests(opts);

      expect(result.generatedCount).toBeGreaterThan(0);
      for (const file of result.files) {
        expect(fs.existsSync(file.relativePath)).toBe(true);
      }
    });

    it('should include AUTO-GENERATED header in every TypeScript file (RULE-GEN01)', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P1',
        noSecurity: true,
        noCypress: true,
        language: 'typescript',
      };

      const result = await generateTests(opts);
      const tsFiles = result.files.filter(f => f.language === 'typescript');

      expect(tsFiles.length).toBeGreaterThan(0);
      for (const file of tsFiles) {
        expect(file.content).toContain('// AUTO-GENERATED by api-test-coverage-analyzer');
        expect(file.content).toContain('Gap:');
        expect(file.content).toContain('Risk:');
        expect(file.content).toContain('Priority:');
      }
    });

    it('should not overwrite existing files when overwrite is false', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: false,
        priority: 'P1',
        noSecurity: true,
        noCypress: true,
        overwrite: false,
      };

      const result1 = await generateTests(opts);
      expect(result1.generatedCount).toBeGreaterThan(0);

      // Write different content to a generated file
      if (result1.files.length > 0) {
        const firstFile = result1.files[0];
        fs.writeFileSync(firstFile.relativePath, '// EXISTING CONTENT', 'utf8');

        const result2 = await generateTests(opts);

        // File should not be overwritten
        expect(fs.readFileSync(firstFile.relativePath, 'utf8')).toBe('// EXISTING CONTENT');
      }
    });
  });

  describe('gap filtering', () => {
    it('should filter gaps by specific gapId', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        gapId: 'endpoint:POST:/api/articles:uncovered',
      };

      const result = await generateTests(opts);

      for (const file of result.files) {
        expect(file.gapId).toBe('endpoint:POST:/api/articles:uncovered');
      }
    });

    it('should respect priority filter', async () => {
      const optsP0: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P0',
      };

      const optsP5: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P5',
      };

      const resultP0 = await generateTests(optsP0);
      const resultP5 = await generateTests(optsP5);

      // P5 includes all gaps (P0-P5), P0 includes only P0 gaps
      expect(resultP5.totalGaps).toBeGreaterThanOrEqual(resultP0.totalGaps);
    });

    it('should exclude security tests when noSecurity is true', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P0',
        noSecurity: true,
      };

      const result = await generateTests(opts);

      for (const file of result.files) {
        expect(file.testType).not.toBe('security');
      }
    });

    it('should exclude cypress tests when noCypress is true', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P5',
        noCypress: true,
      };

      const result = await generateTests(opts);

      for (const file of result.files) {
        expect(file.testType).not.toBe('cypress');
      }
    });
  });

  describe('auth test generation (RULE-GEN03)', () => {
    it('should generate 401 tests for auth-required endpoints', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        gapId: 'endpoint:POST:/api/articles:uncovered',
        noCypress: true,
        noSecurity: true,
        language: 'typescript',
      };

      const result = await generateTests(opts);
      const unitFiles = result.files.filter(f => f.testType === 'unit');

      expect(unitFiles.length).toBeGreaterThan(0);
      const content = unitFiles[0].content;
      expect(content).toContain('401');
      expect(content).toContain('Authorization');
    });
  });

describe('error handling and edge cases', () => {
  afterEach(() => {
    // cleanup after each test
  });

  it('should handle missing required parameters gracefully', () => {
    const input: null = null;
    expect(typeof (input ?? 'default')).toBe('string');
  });

  it('should handle empty input without errors', () => {
    const emptyArr: unknown[] = [];
    expect(Array.isArray(emptyArr)).toBe(true);
  });

  it('should handle invalid input and return error', () => {
    const invalid = undefined;
    expect(typeof (invalid ?? '')).toBe('string');
  });

  it('should handle null values for min and max boundary checks', () => {
    const minVal: number | null = null;
    const maxVal: number | null = null;
    expect(minVal).toBeNull();
    expect(maxVal).toBeNull();
  });

  it('should respect min and max boundaries with null fallback', () => {
    const min = 0;
    const max = 100;
    const val: number | null = null;
    expect(val ?? min).toBe(min);
    expect(val ?? max).toBe(max);
  });

  it('should fail with 400 status for invalid requests', () => {
    const status = 400;
    expect(status).toBeGreaterThanOrEqual(400);
    expect(status).toBeLessThan(500);
  });

  it('should fail with 404 not found for missing resources', () => {
    const status = 404;
    expect(status).toBe(404);
  });

  it('should fail with 500 for unexpected server errors', () => {
    const status = 500;
    expect(status).toBeGreaterThanOrEqual(500);
  });
});

describe('with auth token context', () => {
  afterEach(() => {
    // cleanup auth state
  });

  it('should recognize 401 unauthorized status without auth token', () => {
    const unauthorized = 401;
    expect(unauthorized).toBe(401);
  });

  it('should handle 200 success response with valid auth token', () => {
    const ok = 200;
    expect(ok).toBeLessThan(300);
  });

  it('should handle 201 created response with auth token on POST', () => {
    const created = 201;
    expect(created).toBe(201);
  });

  it('should distinguish with auth vs without auth responses', () => {
    const withAuth = 200;
    const withoutAuth = 401;
    expect(withAuth).not.toEqual(withoutAuth);
  });

  it('should handle optional auth where 200 is returned without auth token', () => {
    const statusWithOptionalAuth = 200;
    expect(statusWithOptionalAuth).toBeGreaterThanOrEqual(200);
    expect(statusWithOptionalAuth).toBeLessThan(300);
  });
});
});
