/**
 * Feature 28 — Tests for TestGenerationEngine
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { TestGenerationEngine, generateTests } from '../../src/generation/engine';
import type { GenerationOptions } from '../../src/generation/types';

describe('TestGenerationEngine', () => {
  let tmpDir: string;
  let reportsDir: string;
  let outDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'gen-test-'));
    reportsDir = path.join(tmpDir, 'reports');
    outDir = path.join(tmpDir, 'generated-tests');
    fs.mkdirSync(reportsDir, { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  describe('dry-run mode', () => {
    it('should not write files in dry-run mode', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P0',
      };

      const result = await generateTests(opts);

      expect(result.dryRun).toBe(true);
      expect(fs.existsSync(outDir)).toBe(false);
    });

    it('should produce GeneratedFile content in dry-run mode', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P1',
      };

      const result = await generateTests(opts);

      expect(result.files.length).toBeGreaterThan(0);
      for (const file of result.files) {
        expect(file.content).toBeTruthy();
        expect(file.gapId).toBeTruthy();
        expect(file.relativePath).toBeTruthy();
      }
    });
  });

  describe('file generation', () => {
    it('should write files when dryRun is false', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: false,
        priority: 'P1',
        noSecurity: true,
        noCypress: true,
      };

      const result = await generateTests(opts);

      expect(result.generatedCount).toBeGreaterThan(0);
      for (const file of result.files) {
        expect(fs.existsSync(file.relativePath)).toBe(true);
      }
    });

    it('should include AUTO-GENERATED header in every TypeScript file (RULE-GEN01)', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P1',
        noSecurity: true,
        noCypress: true,
        language: 'typescript',
      };

      const result = await generateTests(opts);
      const tsFiles = result.files.filter(f => f.language === 'typescript');

      expect(tsFiles.length).toBeGreaterThan(0);
      for (const file of tsFiles) {
        expect(file.content).toContain('// AUTO-GENERATED by api-test-coverage-analyzer');
        expect(file.content).toContain('Gap:');
        expect(file.content).toContain('Risk:');
        expect(file.content).toContain('Priority:');
      }
    });

    it('should not overwrite existing files when overwrite is false', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: false,
        priority: 'P1',
        noSecurity: true,
        noCypress: true,
        overwrite: false,
      };

      const result1 = await generateTests(opts);
      expect(result1.generatedCount).toBeGreaterThan(0);

      // Write different content to a generated file
      if (result1.files.length > 0) {
        const firstFile = result1.files[0];
        fs.writeFileSync(firstFile.relativePath, '// EXISTING CONTENT', 'utf8');

        const result2 = await generateTests(opts);

        // File should not be overwritten
        expect(fs.readFileSync(firstFile.relativePath, 'utf8')).toBe('// EXISTING CONTENT');
      }
    });
  });

  describe('gap filtering', () => {
    it('should filter gaps by specific gapId', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        gapId: 'endpoint:POST:/api/articles:uncovered',
      };

      const result = await generateTests(opts);

      for (const file of result.files) {
        expect(file.gapId).toBe('endpoint:POST:/api/articles:uncovered');
      }
    });

    it('should respect priority filter', async () => {
      const optsP0: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P0',
      };

      const optsP5: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P5',
      };

      const resultP0 = await generateTests(optsP0);
      const resultP5 = await generateTests(optsP5);

      // P5 includes all gaps (P0-P5), P0 includes only P0 gaps
      expect(resultP5.totalGaps).toBeGreaterThanOrEqual(resultP0.totalGaps);
    });

    it('should exclude security tests when noSecurity is true', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P0',
        noSecurity: true,
      };

      const result = await generateTests(opts);

      for (const file of result.files) {
        expect(file.testType).not.toBe('security');
      }
    });

    it('should exclude cypress tests when noCypress is true', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        priority: 'P5',
        noCypress: true,
      };

      const result = await generateTests(opts);

      for (const file of result.files) {
        expect(file.testType).not.toBe('cypress');
      }
    });
  });

  describe('auth test generation (RULE-GEN03)', () => {
    it('should generate 401 tests for auth-required endpoints', async () => {
      const opts: GenerationOptions = {
        reportsDir,
        outDir,
        dryRun: true,
        gapId: 'endpoint:POST:/api/articles:uncovered',
        noCypress: true,
        noSecurity: true,
        language: 'typescript',
      };

      const result = await generateTests(opts);
      const unitFiles = result.files.filter(f => f.testType === 'unit');

      expect(unitFiles.length).toBeGreaterThan(0);
      const content = unitFiles[0].content;
      expect(content).toContain('401');
      expect(content).toContain('Authorization');
    });
  });
});
