/**
 * Feature 28 — Tests for TemplateRenderer
 */

import { renderTemplate } from '../../src/generation/template-renderer';
import type { GenerationContext } from '../../src/generation/types';

const BASE_CONTEXT: GenerationContext = {
  gap: {
    id: 'endpoint:POST:/api/articles:uncovered',
    type: 'endpoint',
    priority: 'P1',
    riskScore: 85,
  },
  endpoint: {
    method: 'POST',
    path: '/api/articles',
    pathNormalized: '/api/articles',
    operationId: 'createArticle',
    summary: 'Create Article',
    auth: {
      required: true,
      optional: false,
      type: 'jwt',
      headerName: 'Authorization',
      scheme: 'Bearer',
    },
  },
  parameters: [
    {
      name: 'title',
      in: 'body',
      required: true,
      schema: { type: 'string', minLength: 1 },
      missingCases: ['missing-required'],
    },
  ],
  responses: [
    { statusCode: 201, description: 'Created' },
    { statusCode: 401, description: 'Unauthorized' },
    { statusCode: 422, description: 'Unprocessable Entity' },
  ],
  fixtures: {
    validPayload: { title: 'Test Article' },
    invalidPayload: {},
    authToken: 'Bearer <your-test-token>',
    pathParams: {},
  },
  project: {
    name: 'test-api',
    language: 'typescript',
    framework: 'express',
    testFramework: 'jest',
    baseUrl: 'http://localhost:3000',
    importPrefix: '../../src',
  },
};

describe('TemplateRenderer', () => {
  describe('TypeScript / Jest unit test', () => {
    it('should include AUTO-GENERATED header (RULE-GEN01)', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });

      expect(output).toContain('// AUTO-GENERATED by api-test-coverage-analyzer');
      expect(output).toContain('Gap:');
      expect(output).toContain('Risk: 85');
      expect(output).toContain('Priority: P1');
    });

    it('should include TODO comments for placeholder values (RULE-GEN02)', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });

      expect(output).toContain('// TODO:');
    });

    it('should generate 401 tests for auth-required endpoints (RULE-GEN03)', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });

      expect(output).toContain('401');
      expect(output).toContain('Authorization');
    });

    it('should assert on status code before body (RULE-GEN04)', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });

      const statusIdx = output.indexOf('expect(response.status)');
      const bodyIdx = output.indexOf('expect(response.body)');

      if (bodyIdx !== -1) {
        expect(statusIdx).toBeLessThan(bodyIdx);
      }
    });

    it('should NOT use toBeTruthy() for body assertions (RULE-GEN05)', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });

      // Check that no body assertion uses toBeTruthy
      const lines = output.split('\n');
      for (const line of lines) {
        if (line.includes('response.body') && line.includes('toBeTruthy')) {
          fail(`Found weak assertion: ${line}`);
        }
      }
    });

    it('should include supertest import', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });

      expect(output).toContain("import request from 'supertest'");
    });

    it('should include app import from correct path', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });

      expect(output).toContain("import { app } from '../../src/app'");
    });
  });

  describe('TypeScript / Jest security test', () => {
    const securityCtx: GenerationContext = {
      ...BASE_CONTEXT,
      gap: { ...BASE_CONTEXT.gap, type: 'security' },
    };

    it('should include [SEC-AUTH-01] label (RULE-SEC01)', () => {
      const output = renderTemplate(securityCtx, { language: 'typescript', testType: 'security' });

      expect(output).toContain('[SEC-AUTH-01]');
      expect(output).toContain('[SEC-AUTH-02]');
    });

    it('should include injection tests with not.toBe(500) (RULE-SEC02)', () => {
      const output = renderTemplate(securityCtx, { language: 'typescript', testType: 'security' });

      expect(output).toContain('[SEC-INJ-01]');
      expect(output).toContain('not.toBe(500)');
    });

    it('should check XSS response body does not contain script tag (RULE-SEC03)', () => {
      const output = renderTemplate(securityCtx, { language: 'typescript', testType: 'security' });

      expect(output).toContain('[SEC-INJ-02]');
      expect(output).toContain('<script>');
      expect(output).toContain("not.toContain('<script>')");
    });
  });

  describe('Cypress E2E test', () => {
    it('should use cy.request() not cy.visit() (RULE-CY01)', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'cypress' });

      expect(output).toContain('cy.request(');
      expect(output).not.toContain('cy.visit(');
    });

    it('should use failOnStatusCode: false for negative tests (RULE-CY03)', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'cypress' });

      expect(output).toContain('failOnStatusCode: false');
    });
  });

  describe('Python / pytest', () => {
    it('should include AUTO-GENERATED header', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'python', testType: 'unit' });

      expect(output).toContain('# AUTO-GENERATED by api-test-coverage-analyzer');
    });

    it('should include pytest import', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'python', testType: 'unit' });

      expect(output).toContain('import pytest');
    });

    it('should generate 401 assertion for auth-required endpoints', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'python', testType: 'unit' });

      expect(output).toContain('401');
    });
  });

  describe('Java / JUnit5', () => {
    it('should include AUTO-GENERATED header', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'java', testType: 'unit' });

      expect(output).toContain('// AUTO-GENERATED by api-test-coverage-analyzer');
    });

    it('should include @SpringBootTest annotation', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'java', testType: 'unit' });

      expect(output).toContain('@SpringBootTest');
    });

    it('should include 401 test for auth-required endpoints', () => {
      const output = renderTemplate(BASE_CONTEXT, { language: 'java', testType: 'unit' });

      expect(output).toContain('isUnauthorized()');
    });
  });

  describe('Integration flow test', () => {
    const flowCtx: GenerationContext = {
      ...BASE_CONTEXT,
      gap: { ...BASE_CONTEXT.gap, type: 'integration' },
      flow: {
        id: 'create-article-flow',
        name: 'Create and Publish Article',
        steps: [
          { method: 'POST', path: '/api/articles', description: 'Create an article' },
          { method: 'GET', path: '/api/articles/:slug', description: 'Retrieve the article' },
          { method: 'PUT', path: '/api/articles/:slug', description: 'Update the article' },
        ],
        missingStepIndex: 2,
      },
    };

    it('should mark missing step with ⚠️ comment (RULE-INT03)', () => {
      const output = renderTemplate(flowCtx, { language: 'typescript', testType: 'integration' });

      expect(output).toContain('⚠️ MISSING STEP');
    });

    it('should use beforeAll for auth setup (RULE-INT04)', () => {
      const output = renderTemplate(flowCtx, { language: 'typescript', testType: 'integration' });

      expect(output).toContain('beforeAll(');
      expect(output).not.toContain('beforeEach(');
    });

    it('should use sequential it() blocks not nested describe (RULE-INT01)', () => {
      const output = renderTemplate(flowCtx, { language: 'typescript', testType: 'integration' });

      const describeCount = (output.match(/describe\(/g) ?? []).length;
      const itCount = (output.match(/it\(/g) ?? []).length;

      // Only one top-level describe, multiple sequential it() blocks
      expect(describeCount).toBe(1);
      expect(itCount).toBeGreaterThan(1);
    });
  });
});

describe('TemplateRenderer – edge cases and error handling', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should handle missing optional auth gracefully (without auth context)', () => {
    const noAuthCtx: GenerationContext = {
      ...BASE_CONTEXT,
      endpoint: {
        ...BASE_CONTEXT.endpoint,
        auth: { required: false, optional: false, type: undefined, headerName: undefined, scheme: undefined },
      },
    };
    const output = renderTemplate(noAuthCtx, { language: 'typescript', testType: 'unit' });
    expect(typeof output).toBe('string');
    expect(output.length).toBeGreaterThan(0);
  });

  it('should return non-empty string for null-like gap riskScore boundary (riskScore = 0)', () => {
    const zeroRiskCtx: GenerationContext = {
      ...BASE_CONTEXT,
      gap: { ...BASE_CONTEXT.gap, riskScore: 0 },
    };
    const output = renderTemplate(zeroRiskCtx, { language: 'typescript', testType: 'unit' });
    expect(output).toContain('Risk: 0');
  });

  it('should handle empty parameters array without error', () => {
    const noParamsCtx: GenerationContext = {
      ...BASE_CONTEXT,
      parameters: [],
    };
    const output = renderTemplate(noParamsCtx, { language: 'typescript', testType: 'unit' });
    expect(typeof output).toBe('string');
    expect(output.length).toBeGreaterThan(0);
  });

  it('should handle empty responses array without error (boundary: no status codes)', () => {
    const noResponsesCtx: GenerationContext = {
      ...BASE_CONTEXT,
      responses: [],
    };
    const output = renderTemplate(noResponsesCtx, { language: 'typescript', testType: 'unit' });
    expect(typeof output).toBe('string');
  });

  it('should include 401 unauthorized check when auth is required (with auth token)', () => {
    const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });
    expect(output).toContain('401');
    expect(output).toContain('Authorization');
  });

  it('should handle invalid/unknown testType by returning a fallback string', () => {
    const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unknown' as any });
    expect(typeof output).toBe('string');
  });

  it('should handle missing/null flow for integration type without throwing', () => {
    const noFlowCtx: GenerationContext = {
      ...BASE_CONTEXT,
      gap: { ...BASE_CONTEXT.gap, type: 'integration' },
      flow: undefined,
    };
    expect(() => renderTemplate(noFlowCtx, { language: 'typescript', testType: 'integration' })).not.toThrow();
  });

  it('should include 200 or 201 success path alongside 401 auth failure path', () => {
    const output = renderTemplate(BASE_CONTEXT, { language: 'typescript', testType: 'unit' });
    const has200or201 = output.includes('201') || output.includes('200');
    expect(has200or201).toBe(true);
    expect(output).toContain('401');
  });
});
