/**
 * Feature 28 — AiFlowExporter
 * Produces ai-ready-flows.md and ai-ready-flows.json for AI coding assistants.
 */

import * as fs from 'fs';
import * as path from 'path';
import { extractGapsFromReports } from './gap-extractor';
import { buildContext } from './context-builder';
import { renderTemplate } from './template-renderer';
import { routeOutputFile, sortGapsByPriority } from './file-router';
import type {
  AiReadyFlows,
  AiFlowGap,
  AiFlowExporterOptions,
  GapPriority,
  MissingTestCase,
} from './types';

// ─── Priority filter ──────────────────────────────────────────────────────────

const PRIORITY_VALUES: Record<GapPriority, number> = {
  P0: 0, P1: 1, P2: 2, P3: 3, P4: 4, P5: 5,
};

function priorityGte(a: GapPriority, b: GapPriority): boolean {
  return PRIORITY_VALUES[a] <= PRIORITY_VALUES[b];
}

// ─── Copilot prompt builder ───────────────────────────────────────────────────

function buildCopilotPrompt(gap: AiFlowGap, projectName: string, testFramework: string, appImportPath: string): string {
  const lines: string[] = [
    `Generate a ${testFramework} test file at \`${gap.suggestedOutputPath}\` for ${gap.endpoint.method} ${gap.endpoint.path}.`,
    `Import the app: \`import { app } from '${appImportPath}'\`.`,
    `Test cases to cover:`,
  ];

  for (const tc of gap.missingTestCases) {
    lines.push(`- ${tc.description} (expect HTTP ${tc.expectedStatus})`);
  }

  if (gap.endpoint.auth.required) {
    lines.push(`Auth: Required (${gap.endpoint.auth.scheme ?? 'Bearer'} token). Use POST /api/users/login to get a token.`);
  }

  if (gap.existingSimilarTests.length > 0) {
    lines.push(`Follow the pattern in \`${gap.existingSimilarTests[0]}\` for style guidance.`);
  }

  lines.push(`Rules: assert status code BEFORE body; no toBeTruthy(); use specific matchers.`);

  const prompt = lines.join(' ');
  // Truncate to ~800 tokens (~3200 chars as rough estimate)
  return prompt.length > 3200 ? prompt.slice(0, 3197) + '...' : prompt;
}

// ─── Missing test case builder ────────────────────────────────────────────────

function buildMissingTestCases(gap: { type: string; endpoint: { auth: { required: boolean; optional: boolean } }; responses?: Array<{ statusCode: number; description?: string }> }): MissingTestCase[] {
  const cases: MissingTestCase[] = [];
  const successStatus = gap.responses?.find(r => r.statusCode >= 200 && r.statusCode < 300)?.statusCode ?? 200;

  cases.push({ id: 'happy-path', description: 'valid request succeeds', expectedStatus: successStatus });

  if (gap.endpoint.auth.required) {
    cases.push({ id: 'no-auth', description: 'missing auth token', expectedStatus: 401 });
    cases.push({ id: 'invalid-auth', description: 'invalid token', expectedStatus: 401 });
  }

  if (gap.endpoint.auth.optional) {
    cases.push({ id: 'no-auth-optional', description: 'request without auth (optional)', expectedStatus: successStatus });
  }

  const errorResponses = gap.responses?.filter(r => r.statusCode >= 400) ?? [];
  for (const resp of errorResponses.slice(0, 3)) {
    cases.push({
      id: `error-${resp.statusCode}`,
      description: resp.description ?? `error ${resp.statusCode}`,
      expectedStatus: resp.statusCode,
    });
  }

  return cases;
}

// ─── Markdown generator ───────────────────────────────────────────────────────

function buildMarkdown(flows: AiReadyFlows): string {
  const lines: string[] = [
    `# AI-Ready Test Generation Context`,
    `> Generated by api-test-coverage-analyzer | Project: ${flows.project.name} | Analyzed: ${flows.generatedAt.split('T')[0]}`,
    ``,
    `## How to Use This Document`,
    `This document contains structured context for an AI assistant to generate missing tests.`,
    `For each gap section below, instruct your AI: "Generate tests for this gap using the context provided."`,
    ``,
    `---`,
    ``,
  ];

  for (let i = 0; i < flows.gaps.length; i++) {
    const gap = flows.gaps[i];
    lines.push(`## Gap ${i + 1}: ${gap.endpoint.method} ${gap.endpoint.path} — [PRIORITY: ${gap.priority} | RISK: ${gap.riskScore}]`);
    lines.push(``);
    lines.push(`### What Needs Testing`);
    lines.push(`Endpoint \`${gap.endpoint.method} ${gap.endpoint.path}\` is missing test coverage. Tests needed for:`);

    for (const tc of gap.missingTestCases) {
      lines.push(`- ${tc.description} (expect ${tc.expectedStatus})`);
    }

    lines.push(``);
    lines.push(`### Endpoint Contract`);
    lines.push(`- **Method:** ${gap.endpoint.method}`);
    lines.push(`- **Path:** \`${gap.endpoint.path}\``);

    if (gap.endpoint.auth.required) {
      lines.push(`- **Auth:** Required (${gap.endpoint.auth.type ?? 'JWT'} ${gap.endpoint.auth.scheme ?? 'Bearer'} token)`);
    } else {
      lines.push(`- **Auth:** Not required`);
    }

    lines.push(``);
    lines.push(`### Project Context`);
    lines.push(`- **Language:** ${flows.project.language}`);
    lines.push(`- **Test Framework:** ${flows.project.testFramework}`);
    lines.push(`- **App Import:** \`import { app } from '${flows.project.appImportPath}'\``);

    if (gap.existingSimilarTests.length > 0) {
      lines.push(`- **Existing Similar Tests:** See \`${gap.existingSimilarTests[0]}\` for patterns`);
    }

    lines.push(``);
    lines.push(`### Copilot Instructions`);
    lines.push(gap.copilotPrompt);

    if (gap.generatedCode) {
      lines.push(``);
      lines.push(`### Generated Scaffold`);
      lines.push(`\`\`\`typescript`);
      lines.push(gap.generatedCode);
      lines.push(`\`\`\``);
    }

    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  return lines.join('\n');
}

// ─── Similar test finder ──────────────────────────────────────────────────────

function findSimilarTests(apiPath: string): string[] {
  const testsDir = path.join(process.cwd(), 'tests');
  if (!fs.existsSync(testsDir)) return [];

  try {
    const files = fs.readdirSync(testsDir).filter(f => f.endsWith('.test.ts') || f.endsWith('.test.js'));
    // Return up to 2 similar test files
    return files.slice(0, 2).map(f => `tests/${f}`);
  } catch {
    return [];
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function exportAiFlows(opts: AiFlowExporterOptions): Promise<AiReadyFlows> {
  const format = opts.format ?? 'both';
  const maxGaps = opts.maxGaps ?? 50;
  const minPriority = opts.priority ?? 'P3';

  // Load discovery info
  const summaryPath = path.join(opts.reportsDir, 'coverage-summary.json');
  let projectName = 'my-api';
  let language = 'typescript';
  let testFramework = 'jest';
  let appImportPath = '../../src/app';

  if (fs.existsSync(summaryPath)) {
    try {
      const summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8')) as {
        discoveryInfo?: { language?: string; testFramework?: string; appImportPath?: string };
        project?: { name?: string };
      };
      projectName = summary.project?.name ?? projectName;
      language = summary.discoveryInfo?.language ?? language;
      testFramework = summary.discoveryInfo?.testFramework ?? testFramework;
      appImportPath = summary.discoveryInfo?.appImportPath ?? appImportPath;
    } catch {
      // Use defaults
    }
  }

  // Extract and filter gaps
  let gaps = extractGapsFromReports(opts.reportsDir);
  gaps = sortGapsByPriority(gaps.filter(g => priorityGte(g.priority, minPriority)));
  gaps = gaps.slice(0, maxGaps);

  const aiGaps: AiFlowGap[] = [];

  for (const gap of gaps) {
    const suggestedOutputPath = routeOutputFile(gap, 'unit', 'tests', language);
    const discoveryInfo = {
      name: projectName,
      language,
      framework: 'express',
      testFramework,
      baseUrl: 'http://localhost:3000',
      projectRoot: process.cwd(),
      appImportPath,
    };
    const ctx = buildContext(gap, suggestedOutputPath, discoveryInfo);
    const generatedCode = renderTemplate(ctx, { language, testType: 'unit' });
    const missingTestCases = buildMissingTestCases(gap);
    const existingSimilarTests = findSimilarTests(gap.endpoint.path);

    const aiGap: AiFlowGap = {
      gapId: gap.id,
      priority: gap.priority,
      riskScore: gap.riskScore,
      type: gap.type,
      endpoint: {
        method: gap.endpoint.method,
        path: gap.endpoint.path,
        auth: {
          required: gap.endpoint.auth.required,
          type: gap.endpoint.auth.type,
          scheme: gap.endpoint.auth.scheme,
        },
      },
      missingTestCases,
      copilotPrompt: '',
      suggestedOutputPath,
      existingSimilarTests,
      generatedCode,
    };

    aiGap.copilotPrompt = buildCopilotPrompt(aiGap, projectName, testFramework, appImportPath);
    aiGaps.push(aiGap);
  }

  const result: AiReadyFlows = {
    generatedAt: new Date().toISOString(),
    project: {
      name: projectName,
      language,
      testFramework,
      appImportPath,
    },
    gaps: aiGaps,
  };

  // Write outputs
  fs.mkdirSync(opts.outDir, { recursive: true });

  if (format === 'json' || format === 'both') {
    const jsonPath = path.join(opts.outDir, 'ai-ready-flows.json');
    fs.writeFileSync(jsonPath, JSON.stringify(result, null, 2), 'utf8');
    console.log(`AI flows JSON written to: ${jsonPath}`);
  }

  if (format === 'markdown' || format === 'both') {
    const mdPath = path.join(opts.outDir, 'ai-ready-flows.md');
    fs.writeFileSync(mdPath, buildMarkdown(result), 'utf8');
    console.log(`AI flows Markdown written to: ${mdPath}`);
  }

  return result;
}
