source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

# Core framework
gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"

# Authentication & Security
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.7"

# API utilities
gem "kaminari", "~> 1.2"
gem "rack-cors", "~> 2.0"

# Background jobs
gem "sidekiq", "~> 7.0"

# Caching
gem "redis", "~> 5.0"

# Serialization
gem "oj", "~> 3.16"

# HTTP
gem "faraday", "~> 2.7"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.2"
  gem "faker", "~> 3.2"
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

group :test do
  gem "shoulda-matchers", "~> 5.3"
  gem "database_cleaner-active_record", "~> 2.1"
  gem "simplecov", require: false
  gem "simplecov-json", require: false
  gem "rspec_junit_formatter", "~> 0.6"
  gem "webmock", "~> 3.18"
  gem "timecop", "~> 0.9"
end

group :development do
  gem "annotate", "~> 3.2"
  gem "spring"
  gem "listen", "~> 3.8"
end
